# Generated by Django 3.1 on 2023-07-20 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_benh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Vac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_benh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('diachi', models.TextField(max_length=50)),
                ('tenbs', models.CharField(max_length=30, null=True)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='')),
                ('ma_benh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_goc', models.CharField(max_length=30)),
                ('ten_bd', models.CharField(max_length=30)),
                ('gia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50, null=True)),
                ('namsinh', models.DateField()),
                ('gioitinh', models.CharField(max_length=10)),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('thebh', models.CharField(max_length=50)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='')),
                ('qhe', models.CharField(choices=[('0', 'admin'), ('1', 'Ông'), ('2', 'Bà'), ('3', 'Cha'), ('4', 'Mẹ'), ('5', 'Anh'), ('6', 'Chị'), ('7', 'Em'), ('8', 'Cô'), ('9', 'Dì'), ('10', 'Chú'), ('11', 'Bác')], max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vac', models.CharField(max_length=100)),
                ('phan_ung', models.CharField(max_length=100)),
                ('ngay_tiem', models.DateField()),
                ('ngay_hen', models.DateField(null=True)),
                ('dia_chi', models.TextField(max_length=200)),
                ('canhan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.personal')),
                ('ten_benh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.disease_vac')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieuluong', models.IntegerField()),
                ('ma_thuoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medicine')),
                ('ma_toa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.health')),
            ],
        ),
        migrations.AddField(
            model_name='health',
            name='ma_canhan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.personal'),
        ),
    ]
